---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aksnodepublicipcontroller-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aksnodepublicipcontroller-rbac
subjects:
  - kind: ServiceAccount
    name: aksnodepublicipcontroller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
